//
// Created by LEGION on 2025/12/19.
//

#include "LyricObject.hpp"

#include <ranges>

#include <QScreen>

#include "LyricLine.hpp"

QString LyricObject::toASS() {
    const auto header = this->getAssHeader();
    std::span spanLyrics = this->_line_s;
    auto resultView = spanLyrics
                    | std::views::transform([](const LyricLine& line){
                        return line.toASS();
                    });
    return header + QStringList(resultView.begin(), resultView.end()).join("\n");
}

QString LyricObject::getAssHeader() {
    QSize size(1920, 1080);
    // ReSharper disable once CppTooWideScope
    const auto screen = QGuiApplication::primaryScreen();

    if (screen) {
        size = screen->size();
    }

    return QString(R"([Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: %1
ScriptType: v4.00+
Timer: 100.0000
PlayResX: %2
PlayResY: %3
WrapStyle: 0
ScaledBorderAndShadow: no

[Aegisub Project Garbage]
Last Style Storage: Default

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: orig-furigana,Arial,72,&H0000FF&,&H000000&,&HFFFFFF&,&H00000000,0,0,0,0,100,100,6,0,1,5,0,2,10,10,10,128
Style: orig,Arial,128,&H0000FF&,&H000000&,&HFFFFFF&,&H00000000,0,0,0,0,100,100,7.5,0,1,6.5,0,2,10,10,10,1
Style: roma,Arial,52,&H0000FF&,&H000000&,&HFFFFFF&,&H00000000,0,0,0,0,100,100,0,0,1,5,0,2,10,10,255,0
Style: ts,Arial,94,&H0000FF&,&H000000&,&HFFFFFF&,&H00000000,0,0,0,0,100,100,0,0,1,6.5,0,8,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
)").arg(this->getTitle()).arg(size.width()).arg(size.height());
}
